int printString(char * str); 
int readString(char * str);
int readfile(char * filename, char * str);
void type(char * command);
int executeProgram(char * command, int segment);
int compareTo(char * str1, char * str2);
void clear(char * buffer);
int delete(char * fname);
int writeFile(Char * fname, char * buffer, int sectors);
void copyFile(char * line);
void writeFileHelper(char * dest, char * buffer, int sectors);
